# Generated by Django 4.0.4 on 2022-08-23 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=200)),
                ('topic', models.CharField(max_length=200)),
                ('subtopic', models.CharField(max_length=200)),
                ('course_title', models.CharField(max_length=200)),
                ('course_author', models.CharField(max_length=200)),
                ('course_link', models.CharField(max_length=200)),
                ('course_rating', models.IntegerField()),
            ],
        ),
    ]
