# Generated by Django 4.0.4 on 2022-08-25 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=200)),
                ('topic', models.CharField(max_length=200)),
                ('subtopic', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='course',
            name='subtopic',
        ),
        migrations.RemoveField(
            model_name='course',
            name='topic',
        ),
        migrations.AddField(
            model_name='course',
            name='subtopic_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.subtopic'),
        ),
    ]
