# Generated by Django 4.1.2 on 2022-10-14 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favorite_courses',
            field=models.ManyToManyField(related_name='users', to='base.course'),
        ),
    ]
