# Generated by Django 4.1.2 on 2022-10-10 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
